import { useMemo } from 'react';
import { DataSetNames } from '../data-sources/enums/dataset-names';
import { ResultFieldDetail } from '../data-sources/models/data-input-fields';

const commonFields: ResultFieldDetail[] = [
  {
    name: 'category',
    displayName: 'Category',
    groupName: '',
    groupDisplayName: '',
    dataType: '',
    sequenceNo: 0,
  },
  {
    name: 'acn',
    displayName: 'ACN Code',
    groupName: '',
    groupDisplayName: '',
    dataType: '',
    sequenceNo: 1,
  },
  {
    name: 'label',
    displayName: 'Marker label',
    groupName: '',
    groupDisplayName: '',
    dataType: '',
    sequenceNo: 2,
  },
  {
    name: 'unit',
    displayName: 'Unit for marker',
    groupName: '',
    groupDisplayName: '',
    dataType: '',
    sequenceNo: 3,
  },
  {
    name: 'channel',
    displayName: 'Ch',
    groupName: '',
    groupDisplayName: '',
    dataType: '',
    sequenceNo: 4,
    firstLevel: true,
  },
];
const correlationFields: ResultFieldDetail[] = [
  {
    name: 'correlationX',
    displayName: 'Correlation X',
    groupName: 'correlationX',
    groupDisplayName: 'Correlation X',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.Correlation,
    sequenceNo: 5,
  },
  {
    name: 'correlationY',
    displayName: 'Correlation Y',
    groupName: 'correlationY',
    groupDisplayName: 'Correlation Y',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.Correlation,
    sequenceNo: 6,
  },
];
const linearity5Fields: ResultFieldDetail[] = [
  {
    name: 's1FirstTime',
    displayName: 'S-1 Sample 1 1st time',
    groupName: 's1FirstTime',
    groupDisplayName: 'S-1 Sample 1 1st time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 7,
  },
  {
    name: 's1SecondTime',
    displayName: 'S-1 Sample 1 2nd time',
    groupName: 's1SecondTime',
    groupDisplayName: 'S-1 Sample 1 2nd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 8,
  },
  {
    name: 's1ThirdTime',
    displayName: 'S-1 Sample 1 3rd time',
    groupName: 's1ThirdTime',
    groupDisplayName: 'S-1 Sample 1 3rd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 9,
  },
  {
    name: 's2FirstTime',
    displayName: 'S-2 Sample 2 1st time',
    groupName: 's2FirstTime',
    groupDisplayName: 'S-2 Sample 2 1st time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 10,
  },
  {
    name: 's2SecondTime',
    displayName: 'S-2 Sample 2 2nd time',
    groupName: 's2SecondTime',
    groupDisplayName: 'S-2 Sample 2 2nd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 11,
  },
  {
    name: 's2ThirdTime',
    displayName: 'S-2 Sample 2 3rd time',
    groupName: 's2ThirdTime',
    groupDisplayName: 'S-2 Sample 2 3rd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 12,
  },
  {
    name: 's3FirstTime',
    displayName: 'S-3 Sample 3 1st time',
    groupName: 's3FirstTime',
    groupDisplayName: 'S-3 Sample 3 1st time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 13,
  },
  {
    name: 's3SecondTime',
    displayName: 'S-3 Sample 3 2nd time',
    groupName: 's3SecondTime',
    groupDisplayName: 'S-3 Sample 3 2nd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 14,
  },
  {
    name: 's3ThirdTime',
    displayName: 'S-3 Sample 3 3rd time',
    groupName: 's3ThirdTime',
    groupDisplayName: 'S-3 Sample 3 3rd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 15,
  },
  {
    name: 's4FirstTime',
    displayName: 'S-4 Sample 4 1st time',
    groupName: 's4FirstTime',
    groupDisplayName: 'S-4 Sample 4 1st time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 16,
  },
  {
    name: 's4SecondTime',
    displayName: 'S-4 Sample 4 2nd time',
    groupName: 's4SecondTime',
    groupDisplayName: 'S-4 Sample 4 2nd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 17,
  },
  {
    name: 's4ThirdTime',
    displayName: 'S-4 Sample 4 3rd time',
    groupName: 's4ThirdTime',
    groupDisplayName: 'S-4 Sample 4 3rd time',
    dataType: 'array',
    size: 6,
    dataSetName: DataSetNames.Linearity5,
    sequenceNo: 18,
  },
];
const linearity10Fields: ResultFieldDetail[] = [
  {
    name: 's1FirstTime',
    displayName: 'S-1 Sample 1 1st time',
    groupName: 's1FirstTime',
    groupDisplayName: 'S-1 Sample 1 1st time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 19,
  },
  {
    name: 's1SecondTime',
    displayName: 'S-1 Sample 1 2nd time',
    groupName: 's1SecondTime',
    groupDisplayName: 'S-1 Sample 1 2nd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 20,
  },
  {
    name: 's1ThirdTime',
    displayName: 'S-1 Sample 1 3rd time',
    groupName: 's1ThirdTime',
    groupDisplayName: 'S-1 Sample 1 3rd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 21,
  },
  {
    name: 's2FirstTime',
    displayName: 'S-2 Sample 2 1st time',
    groupName: 's2FirstTime',
    groupDisplayName: 'S-2 Sample 2 1st time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 22,
  },
  {
    name: 's2SecondTime',
    displayName: 'S-2 Sample 2 2nd time',
    groupName: 's2SecondTime',
    groupDisplayName: 'S-2 Sample 2 2nd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 23,
  },
  {
    name: 's2ThirdTime',
    displayName: 'S-2 Sample 2 3rd time',
    groupName: 's2ThirdTime',
    groupDisplayName: 'S-2 Sample 2 3rd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 24,
  },
  {
    name: 's3FirstTime',
    displayName: 'S-3 Sample 3 1st time',
    groupName: 's3FirstTime',
    groupDisplayName: 'S-3 Sample 3 1st time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 25,
  },
  {
    name: 's3SecondTime',
    displayName: 'S-3 Sample 3 2nd time',
    groupName: 's3SecondTime',
    groupDisplayName: 'S-3 Sample 3 2nd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 26,
  },
  {
    name: 's3ThirdTime',
    displayName: 'S-3 Sample 3 3rd time',
    groupName: 's3ThirdTime',
    groupDisplayName: 'S-3 Sample 3 3rd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 27,
  },
  {
    name: 's4FirstTime',
    displayName: 'S-4 Sample 4 1st time',
    groupName: 's4FirstTime',
    groupDisplayName: 'S-4 Sample 4 1st time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 28,
  },
  {
    name: 's4SecondTime',
    displayName: 'S-4 Sample 4 2nd time',
    groupName: 's4SecondTime',
    groupDisplayName: 'S-4 Sample 4 2nd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 29,
  },
  {
    name: 's4ThirdTime',
    displayName: 'S-4 Sample 4 3rd time',
    groupName: 's4ThirdTime',
    groupDisplayName: 'S-4 Sample 4 3rd time',
    dataType: 'array',
    size: 11,
    dataSetName: DataSetNames.Linearity10,
    sequenceNo: 30,
  },
];
const accuracyFields: ResultFieldDetail[] = [
  {
    name: 's1-cal',
    displayName: 'S1: Cal1',
    groupName: 's1-cal',
    groupDisplayName: 'S1: Cal1',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 100,
  },
  {
    name: 's2-cal',
    displayName: 'S2: Cal2',
    groupName: 's2-cal',
    groupDisplayName: 'S2: Cal2',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 101,
  },
  {
    name: 's3-cal',
    displayName: 'S3: Cal3',
    groupName: 's3-cal',
    groupDisplayName: 'S3: Cal3',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 102,
  },
  {
    name: 's4-cal',
    displayName: 'S4: Cal4',
    groupName: 's4-cal',
    groupDisplayName: 'S4: Cal4',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 103,
  },
  {
    name: 's5-cal',
    displayName: 'S5: Cal5',
    groupName: 's5-cal',
    groupDisplayName: 'S5: Cal5',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 104,
  },
  {
    name: 's6-cal',
    displayName: 'S6: Cal6',
    groupName: 's6-cal',
    groupDisplayName: 'S6: Cal6',
    dataType: 'array',
    size: 4,
    dataSetName: DataSetNames.Accuracy,
    disableDataMapping: true,
    sequenceNo: 105,
  },
  {
    name: 's1AbsCutoff',
    displayName: 'S1Abs',
    groupName: 's1Abs-cutoff',
    groupDisplayName: 'S1Abs/cutoff',
    dataType: 'number',
    size: null,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 106,
  },
  {
    name: 'k',
    displayName: 'K',
    groupName: 's1Abs-cutoff',
    groupDisplayName: 'S1Abs/cutoff',
    dataType: 'number',
    size: null,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 107,
  },
  {
    name: 'a',
    displayName: 'A',
    groupName: 's1Abs-cutoff',
    groupDisplayName: 'S1Abs/cutoff',
    dataType: 'number',
    size: null,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 108,
  },
  {
    name: 'b',
    displayName: 'B',
    groupName: 's1Abs-cutoff',
    groupDisplayName: 'S1Abs/cutoff',
    dataType: 'number',
    size: null,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 109,
  },
  {
    name: 's1',
    displayName: 'S1: Sample 1',
    groupName: 's1',
    groupDisplayName: 'S1: Sample 1',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 110,
  },
  {
    name: 's2',
    displayName: 'S2: Sample 2',
    groupName: 's2',
    groupDisplayName: 'S2: Sample 2',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 111,
  },
  {
    name: 's3',
    displayName: 'S3: Sample 3',
    groupName: 's3',
    groupDisplayName: 'S3: Sample 3',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 112,
  },
  {
    name: 's4',
    displayName: 'S4: Sample 4',
    groupName: 's4',
    groupDisplayName: 'S4: Sample 4',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 113,
  },
  {
    name: 's5',
    displayName: 'S5: Sample 5',
    groupName: 's5',
    groupDisplayName: 'S5: Sample 5',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 114,
  },
  {
    name: 's6',
    displayName: 'S6: Sample 6',
    groupName: 's6',
    groupDisplayName: 'S6: Sample 6',
    dataType: 'array',
    size: 10,
    dataSetName: DataSetNames.Accuracy,
    sequenceNo: 115,
  },
];
const repeatabilityFields: ResultFieldDetail[] = [
  {
    name: 's1',
    displayName: 'S1: Sample 1',
    groupName: 's1',
    groupDisplayName: 'S1: Sample 1',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 120,
  },
  {
    name: 's2',
    displayName: 'S2: Sample 2',
    groupName: 's2',
    groupDisplayName: 'S2: Sample 2',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 121,
  },
  {
    name: 's3',
    displayName: 'S3: Sample 3',
    groupName: 's3',
    groupDisplayName: 'S3: Sample 3',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 122,
  },
  {
    name: 's4',
    displayName: 'S4: Sample 4',
    groupName: 's4',
    groupDisplayName: 'S4: Sample 4',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 123,
  },
  {
    name: 's5',
    displayName: 'S5: Sample 5',
    groupName: 's5',
    groupDisplayName: 'S5: Sample 5',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 124,
  },
  {
    name: 's6',
    displayName: 'S6: Sample 6',
    groupName: 's6',
    groupDisplayName: 'S6: Sample 6',
    dataType: 'array',
    size: 30,
    dataSetName: DataSetNames.Repeatability,
    sequenceNo: 125,
  },
];
const indoorReproducibilityFields: ResultFieldDetail[] = [
  {
    name: 's1',
    displayName: 'S1: Sample 1',
    groupName: 's1',
    groupDisplayName: 'S1: Sample 1',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 150,
  },
  {
    name: 's2',
    displayName: 'S2: Sample 2',
    groupName: 's2',
    groupDisplayName: 'S2: Sample 2',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 151,
  },
  {
    name: 's3',
    displayName: 'S3: Sample 3',
    groupName: 's3',
    groupDisplayName: 'S3: Sample 3',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 152,
  },
  {
    name: 's4',
    displayName: 'S4: Sample 4',
    groupName: 's4',
    groupDisplayName: 'S4: Sample 4',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 153,
  },
  {
    name: 's5',
    displayName: 'S5: Sample 5',
    groupName: 's5',
    groupDisplayName: 'S5: Sample 5',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 154,
  },
  {
    name: 's6',
    displayName: 'S6: Sample 6',
    groupName: 's6',
    groupDisplayName: 'S6: Sample 6',
    dataType: 'array',
    size: 60,
    dataSetName: DataSetNames.IndoorReproducibility,
    sequenceNo: 155,
  },
];
const correlationQualitativeFields: ResultFieldDetail[] = [
  {
    name: 'correlationX',
    displayName: 'Correlation X',
    groupName: 'correlationX',
    groupDisplayName: 'Correlation X',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.CorrelationQualitative,
    sequenceNo: 160,
  },
  {
    name: 'correlationY',
    displayName: 'Correlation Y',
    groupName: 'correlationY',
    groupDisplayName: 'Correlation Y',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.CorrelationQualitative,
    sequenceNo: 161,
  },
  {
    name: 'correlationX-Reex',
    displayName: 'Correlation X Re-examination',
    groupName: 'correlationX-Reex',
    groupDisplayName: 'Correlation X Re-examination',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.CorrelationQualitative,
    sequenceNo: 162,
  },
  {
    name: 'correlationY-Reex',
    displayName: 'Correlation Y Re-examination',
    groupName: 'correlationY-Reex',
    groupDisplayName: 'Correlation Y Re-examination',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.CorrelationQualitative,
    sequenceNo: 163,
  },
];
const xResidualFields: ResultFieldDetail[] = [
  {
    name: 'correlationX',
    displayName: 'Correlation X',
    groupName: 'correlationX',
    groupDisplayName: 'Correlation X',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.XResidual,
    sequenceNo: 170,
  },
  {
    name: 'correlationY',
    displayName: 'Correlation Y',
    groupName: 'correlationY',
    groupDisplayName: 'Correlation Y',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.XResidual,
    sequenceNo: 171,
  },
  {
    name: 'correlationX-Reex',
    displayName: 'Correlation X Re-examination',
    groupName: 'correlationX-Reex',
    groupDisplayName: 'Correlation X Re-examination',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.XResidual,
    sequenceNo: 172,
  },
  {
    name: 'correlationY-Reex',
    displayName: 'Correlation Y Re-examination',
    groupName: 'correlationY-Reex',
    groupDisplayName: 'Correlation Y Re-examination',
    dataType: 'array',
    size: 50,
    dataSetName: DataSetNames.XResidual,
    sequenceNo: 173,
  },
];

const allDataInputFields = [
  {
    dataSetName: DataSetNames.Correlation,
    fields: correlationFields,
  },
  {
    dataSetName: DataSetNames.Linearity5,
    fields: linearity5Fields,
  },
  {
    dataSetName: DataSetNames.Linearity10,
    fields: linearity10Fields,
  },
  {
    dataSetName: DataSetNames.Accuracy,
    fields: accuracyFields,
  },
  {
    dataSetName: DataSetNames.IndoorReproducibility,
    fields: indoorReproducibilityFields,
  },
  {
    dataSetName: DataSetNames.Repeatability,
    fields: repeatabilityFields,
  },
  {
    dataSetName: DataSetNames.CorrelationQualitative,
    fields: correlationQualitativeFields,
  },
  {
    dataSetName: DataSetNames.XResidual,
    fields: xResidualFields,
  },
];

function useDataInputFields(dataSetName: string) {
  const dataSetFields = useMemo(() => {
    const localDataSetFields =
      allDataInputFields?.find(
        (dataSetFields) => dataSetFields?.dataSetName === dataSetName,
      )?.fields || [];

    return [...commonFields, ...localDataSetFields];
  }, [allDataInputFields, dataSetName, commonFields]);

  return dataSetFields;
}

export default useDataInputFields;
