export enum ValidationTestsCode {
  Correlation = 'correlation',
  ListCorrelation = 'list-correlation',
  CorrelationXResidual = 'correlation-x-residual',
  CorrelationQualitative = 'correlation-qualitative',
  ListCorrelationQualitative = 'list-correlation-qualitative',
  Accuracy = 'accuracy',
  ListAccuracy = 'list-accuracy',
  RepeatabilityReproducibility = 'repeatability',
  ListRepeatabilityReproducibility = 'list-repeataility',
  IndoorReproducibilityDayDifferenceReproducibility = 'indoor-reproducibility',
  ListIndoorReproducibilityDayDifferenceReproducibility = 'list-indoor-reproducibility',
  DetectionSensitivity2SD = 'detection-sensitivity-2sd',
  SpecificitySelectivity = 'influence-of-coexisting-substances',
  LoB = 'lob',
  'LoB-LoD' = 'lob-limit-of-detection',
  LoQ = 'loq-limit-of-quantitation',
  Linearity10 = 'linearity-10-steps',
  Linearity5 = 'linearity-5-steps',
}
